#============================================================================================
# OpenWrt 一体化工作流
# 功能：选择源码 → 生成配置 → 自动保存到仓库 → 全自动编译固件 → 发布Release
#============================================================================================
name: OpenWrt 配置生成+自动编译一体化

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      source_repo:
        description: "选择 OpenWrt 源码仓库"
        required: true
        default: "kygs-immortalwrt-master"
        type: choice
        options:
          - lede-master
          - openwrt-main
          - openwrt-24.10
          - openwrt-23.05
          - immortalwrt-master
          - immortalwrt-24.10
          - istoreos-master
          - kygs-immortalwrt-master
          
      version_tag:
        description: "选择源码版本 Tag（ latest = 最新代码）"
        required: true
        default: "latest"
        type: choice
        options:
          - latest
          - v24.10.0
          - v24.10.1
          - v23.05.0
          - v23.05.1
          - v23.05.2
          - v23.05.3
          - v23.05.4
          
      ssh:
        description: "启用 SSH 连接（可在线 make menuconfig）"
        required: false
        default: false
        type: boolean
        
      config_save_path:
        description: "配置文件保存到仓库的路径（默认即可）"
        required: true
        default: ".config"
        type: text
        
env:
  FEEDS_CONF: feeds.conf.default
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  TZ: Asia/Shanghai
  UPLOAD_RELEASE: true


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 检查项目分支
      uses: actions/checkout@main
    - name: 初始化编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir      
   
    - name: 克隆源代码
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b openwrt

  
        
    - name: SSH连接操作
      uses: P3TERX/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    #- name: SSH连接操作
      #uses: P3TERX/debugger-action@master
      #if: env.SSH_ACTIONS == 'true' || contains(github.event.action, 'ssh')

   
    - name: 检查空间使用情况
      if: (!cancelled())
      run: df -hT

    - name: 上传bin目录
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: 组织文件
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: 上传固件目录
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: 生成发布标签
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        touch release.txt
        [ ${UPLOAD_GOFILE} = true && ${{ steps.gofile.outputs.url }} ] && echo "🔗 [GoFile](${{ steps.gofile.outputs.url }})" >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: 上传固件以发布
      uses: softprops/action-gh-release@master
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*

    - name: 删除工作流运行
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2

    - name: 删除旧版本
      uses: dev-drprasad/delete-older-releases@master
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
